### ISSUE TITLE
hi, where is the pretrian model for real color images?

### ISSUE THREAD

**Issue by zhangyunming** [jiaxi-jiang/FBCNN#2]
ruti

thanks

**Comment by jiaxi-jiang** [comment]
Hi, thanks for your interest!

Currently we only provide the pre-trained models that are used in our paper. In the section of real jpeg comparisons in our paper, for a fair comparison, we use the grayscale model to recover the Y channel and concatenate the recovered Y channel and original Cb, Cr channels into color images, because DCSC and DnCNN are only trained on the Y channel.

For real color images, we believe you can get desirable results using the model, that is trained with single JPEG color images, by setting different input quality factors, because FBCNN is a flexible model. Or you can also retrain the model with our proposed double JPEG degradation models using color images. We will release the training code later.
